id = "tokyo-night-blurred"
name = "Tokyo Night Blurred Theme"
version = "0.1.0"
schema_version = 1
authors = ["hacr <hampus.cronholm@proton.me>"]
description = "Tokyo Night Blurred Theme"
repository = ""
